create table if not exists public.app_broadcasts (
  id uuid primary key default gen_random_uuid(),
  channel text not null,
  title text null,
  message text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_broadcasts_channel_starts_at_idx
  on public.app_broadcasts (channel, starts_at desc);

alter table public.app_broadcasts enable row level security;

create policy "app_broadcasts_read"
  on public.app_broadcasts
  for select
  using (true);

create policy "app_broadcasts_insert"
  on public.app_broadcasts
  for insert
  with check (true);

create policy "app_broadcasts_update"
  on public.app_broadcasts
  for update
  using (true);

create policy "app_broadcasts_delete"
  on public.app_broadcasts
  for delete
  using (true);


create table if not exists public.app_analytics_sessions (
  session_id text primary key,
  user_id uuid null,
  timezone text null,
  user_agent text null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_analytics_sessions_last_seen_idx
  on public.app_analytics_sessions (last_seen_at desc);

alter table public.app_analytics_sessions enable row level security;

create policy "app_analytics_sessions_read"
  on public.app_analytics_sessions
  for select
  using (true);

create policy "app_analytics_sessions_insert"
  on public.app_analytics_sessions
  for insert
  with check (true);

create policy "app_analytics_sessions_update"
  on public.app_analytics_sessions
  for update
  using (true);

create policy "app_analytics_sessions_delete"
  on public.app_analytics_sessions
  for delete
  using (true);


create table if not exists public.app_analytics_page_views (
  id bigint generated by default as identity primary key,
  session_id text not null references public.app_analytics_sessions (session_id) on delete cascade,
  user_id uuid null,
  path text not null,
  title text null,
  referrer text null,
  created_at timestamptz not null default now()
);

create index if not exists app_analytics_page_views_created_idx
  on public.app_analytics_page_views (created_at desc);

create index if not exists app_analytics_page_views_path_created_idx
  on public.app_analytics_page_views (path, created_at desc);

alter table public.app_analytics_page_views enable row level security;

create policy "app_analytics_page_views_read"
  on public.app_analytics_page_views
  for select
  using (true);

create policy "app_analytics_page_views_insert"
  on public.app_analytics_page_views
  for insert
  with check (true);

create policy "app_analytics_page_views_delete"
  on public.app_analytics_page_views
  for delete
  using (true);


create table if not exists public.app_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  provider text null,
  plan text null,
  status text not null default 'active',
  started_at timestamptz null,
  ended_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_subscriptions_status_idx
  on public.app_subscriptions (status, created_at desc);

alter table public.app_subscriptions enable row level security;

create policy "app_subscriptions_read"
  on public.app_subscriptions
  for select
  using (true);

create policy "app_subscriptions_insert"
  on public.app_subscriptions
  for insert
  with check (true);

create policy "app_subscriptions_update"
  on public.app_subscriptions
  for update
  using (true);

create policy "app_subscriptions_delete"
  on public.app_subscriptions
  for delete
  using (true);


create or replace function public.analytics_top_pages(days integer default 7, max_rows integer default 10)
returns table(path text, views bigint, unique_sessions bigint)
language sql
stable
as $$
  select
    path,
    count(*)::bigint as views,
    count(distinct session_id)::bigint as unique_sessions
  from public.app_analytics_page_views
  where created_at >= now() - make_interval(days => days)
  group by path
  order by views desc
  limit max_rows;
$$;


create or replace function public.analytics_usage_summary(days integer default 7)
returns table(sessions bigint, active_sessions_24h bigint, avg_seconds numeric, total_seconds numeric)
language sql
stable
as $$
  select
    count(*)::bigint as sessions,
    count(*) filter (where last_seen_at >= now() - interval '24 hours')::bigint as active_sessions_24h,
    coalesce(avg(extract(epoch from (last_seen_at - first_seen_at))), 0)::numeric as avg_seconds,
    coalesce(sum(extract(epoch from (last_seen_at - first_seen_at))), 0)::numeric as total_seconds
  from public.app_analytics_sessions
  where last_seen_at >= now() - make_interval(days => days);
$$;

